"""
c_tests/b_system/b_generation/d_test_factory_materializer.py
==========================================================
Especificação executável do fluxo integrado ProjectPlan -> Factory -> Artifacts -> Materializer.
Valida que a materialização consome artefatos reais produzidos pela fábrica e os grava fisicamente
no diretório do projeto, sem criação manual artificial de arquivos pelo próprio teste.
"""
from pathlib import Path
from unittest.mock import MagicMock
import pytest

from a_platform.h_factory.a_project_factory import ProjectFactory
from a_platform.i_materializer.a_materializer import ArtifactMaterializer
from a_platform.b_contracts.i_execution_context import ExecutionContext
from a_platform.b_contracts.a_project import ProjectContext
from a_platform.b_contracts.e_task import ProjectTask
from a_platform.b_contracts.g_artifact import Artifact


def test_factory_to_materializer_integration(tmp_path: Path):
    """Valida o handoff completo: Factory produz artefato -> Materializer grava em disco."""
    project_dir = tmp_path / "e_generated_projects" / "prj_fac_mat"
    project_dir.mkdir(parents=True, exist_ok=True)

    task = ProjectTask(
        task_id="t1",
        name="Generate ETL",
        assigned_agent="DataAgent",
        expected_artifacts=["pipeline.py"],
    )
    pctx = ProjectContext(
        project_id="prj_fac_mat",
        project_name="Integration Test",
        project_path=str(project_dir),
        plan=[task],
    )
    ctx = ExecutionContext(project_id="prj_fac_mat", project_context=pctx)

    # Factory produz artefato
    produced_artifact = Artifact(
        identity="art_etl",
        name="pipeline.py",
        path="pipeline.py",
        type="code",
        content="print('ETL generated by factory')\n",
    )
    agent_mock = MagicMock()
    agent_mock.execute_task.return_value = [produced_artifact]
    agent_factory = MagicMock()
    agent_factory.get_agent.return_value = agent_mock

    factory = ProjectFactory(agent_factory=agent_factory)
    artifacts = factory.generate(ctx)
    assert len(artifacts) == 1

    # Materializer persiste no disco
    # O mock de MCP repassa a gravação real para o filesystem temporário
    def mock_mcp_execute(payload):
        if payload.get("action") == "write":
            fpath = Path(payload["path"])
            fpath.parent.mkdir(parents=True, exist_ok=True)
            fpath.write_text(payload.get("content", ""))
            return {"success": True}
        return {"success": True}

    mcp_mock = MagicMock()
    mcp_mock.execute.side_effect = mock_mcp_execute

    materializer = ArtifactMaterializer(mcp=mcp_mock)
    mat_result = materializer.materialize(ctx, artifacts)

    assert mat_result.status == "PASSED"
    # O arquivo físico deve existir agora em disco, gravado pelo materializer
    physical_file = project_dir / "pipeline.py"
    assert physical_file.exists()
    assert "ETL generated by factory" in physical_file.read_text()
