import os
import re
from typing import List
from a_platform.a_core.b_domain.artifact import Artifact
from a_platform.f_llm_gateway.gateway import LLMGateway

class ProjectFactory:
    def __init__(self):
        self.gateway = LLMGateway()

    async def generate_project(self, plan, discovery, profiling) -> List[Artifact]:
        """
        Orchestrates code generation by dynamically calling the LLM Gateway 
        using the context (discovery, profiling, plan tasks).
        """
        prompt = f"""
        Generate Python code for this project based on:
        Objective: {getattr(discovery, 'project_objective', 'Unknown')}
        Domain: {getattr(discovery, 'domain', 'generic')}
        Plan Tasks: {getattr(plan, 'tasks', [])}
        
        Please return the files formatted in markdown code blocks with the filename in the header.
        Example:
        ```python:requirements.txt
        pandas
        ```
        """
        
        response_text = self.gateway.generate(prompt)
        artifacts = self._parse_llm_response(response_text)
        
        # Se falhou por algum motivo (LLM retornou algo invalido), injetamos um basico
        if not artifacts:
            print("[Factory] LLM parsing yielded no artifacts. Using fallback empty main.")
            artifacts.append(Artifact(name="main.py", path="main.py", content="# Generated by AAF\\n"))
            
        return artifacts

    def _parse_llm_response(self, text: str) -> List[Artifact]:
        artifacts = []
        # Procura por blocos do tipo ```python:arquivo.py
        pattern = re.compile(r'```[a-z]*:?([\\w\\.-]+)\\n(.*?)```', re.DOTALL)
        matches = pattern.findall(text)
        
        for filename, content in matches:
            # Garante que as linhas vazias/novas linhas passem certas
            artifacts.append(Artifact(name=filename, path=filename, content=content))
            
        return artifacts
