from typing import Optional, List
from a_platform.a_core.b_domain.artifact import Artifact
from a_platform.a_core.b_domain.project_plan import ProjectPlan
from a_platform.f_llm_gateway.gateway import LLMGateway
from a_platform.c_agents.l_documentation.prompt_templates.doc_prompts import DOC_SYSTEM_PROMPT, DOC_USER_PROMPT

class DocumentationAgent:
    def __init__(self, gateway: Optional[LLMGateway] = None):
        self.gateway = gateway or LLMGateway()

    async def execute(self, plan: ProjectPlan, artifacts: List[Artifact]) -> Artifact:
        artifact_names = [a.name for a in artifacts]
        prompt = DOC_USER_PROMPT.format(
            project_id=plan.project_id,
            project_plan=plan.model_dump_json(indent=2),
            artifacts=", ".join(artifact_names)
        )
        
        readme_content = await self.gateway.generate(
            prompt, 
            complexity="medium", 
            system_prompt=DOC_SYSTEM_PROMPT
        )
        
        # Simple mock fallback if LLM Gateway is mocked
        if "Mocked Response" in readme_content:
            readme_content = f"""# Analytics Project: {plan.project_id}

## Description
This project was automatically generated by Analytics AI Factory.

## Architecture
```mermaid
graph TD;
    A-->B;
```

## Running
Run `docker-compose up`

## Files
{", ".join(artifact_names)}
"""

        return Artifact(
            name="README.md",
            path="README.md",
            content=readme_content
        )
