#!/usr/bin/env python3
import sys
import os

# Garantir que o repositório raiz está no path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from a_platform.b_interfaces.b_cli.a_cli import main

if __name__ == "__main__":
    main()
